### PR TITLE
User-Level Permissions (Merging to Develop Branch)

### PR DESCRIPTION
**Pull request by sandy-abrightmind**
Trying to merge to the develop branch instead of master branch.

### CODE REVIEW

**Comment by boboldehampsink** [comment]
That's better

**Comment by sandy-abrightmind** [comment]
Ok. Awesome! =) I had to select your develop branch with my master branch. 

Thanks!! =)

**Comment by boboldehampsink** [comment]
Please do not submit your .idea files. Also, it looks like this PR also contains other fixes. Next to that, i'd like you to work on the develop branch in stead of the master branch.

**Comment by sandy-abrightmind** [comment]
I do not know what a “.idea" file is or how it’s being added to the project.

If the PR contains other fixes — it’s the first one that I sent you months ago (User Level Permissions).  And I don’t know much about Github. I don’t know how to work on the develop branch — I was just trying to fix the code so that it would work in Craft. I asked you before I sent the PR how you wanted it submitted.

Thanks,
Sandy

**Pull request closed without merging**
