### PR TITLE
Master

### PR DESCRIPTION
**Pull request by sandy-abrightmind**
- Updated the sources for the “All notifications” option so that it
  only displayed the notifications for the apps that the user has
  permissions for.
- If the user is an admin account, it will get a list of all apps
  notifications.

### CODE REVIEW

**Comment by sandy-abrightmind** [comment]
I have completed adding User-Level Permissions for Push Notifications. =)

Thanks!
Sandy Davis

**Comment by boboldehampsink** [comment]
Can you merge into the `develop` branch instead of `master`?

**Comment by sandy-abrightmind** [comment]
How do I merge it into the develop branch instead of the master?

**Comment by boboldehampsink** [comment]
screen shot 2015-11-09 at 16 08 26

**Comment by sandy-abrightmind** [comment]
When I click that, what button do I click to merge them?? Because all it says "Able to merge, these branches can be automatically merged."

**Comment by sandy-abrightmind** [comment]
Do I just create another pull request??

**Comment by boboldehampsink** [comment]
Ah, I do the merging - you just have to issue a merge (pull) request to develop, instead of master.

**Comment by sandy-abrightmind** [comment]
Do I do this from my project page?
screen shot 2015-11-09 at 9 17 08 am

**Comment by boboldehampsink** [comment]
Yes

**Comment by sandy-abrightmind** [comment]
Ok, well I did that... and now it gives me a button to merge the pull request....

**Comment by boboldehampsink** [comment]
Go here: https://github.com/boboldehampsink/pushnotifications/compare

**Comment by sandy-abrightmind** [comment]
I can't do anything on that page. It doesn't allow me to create a pull request from there.
Maybe I need to create a new pull request that connects my project to your projects "develop" branch??

**Comment by boboldehampsink** [comment]
I'm clueless

**Comment by sandy-abrightmind** [comment]
Ok. I did it from my master to your develop branch. Did that work?? I'm clueless too... I've never done any of this in Github.

Sorry....

**Pull request closed without merging**
